# config.yaml
dataset_name: "internal_rxrx"
chunk_size: 2048
batch_size: 512
num_workers: 4
shuffle: true
data_source: "obsm"
obsm_key: "scVI"

optimizer_name: "adamw"
lr: 0.0001
weight_decay: 1e-6
scheduler_name: "warmup_cosine"
min_lr: 0.0
warmup_start_lr: 3e-5
warmup_epochs: 10
lr_decay_steps: [60, 80]
scheduler_interval: "step"
seed: 42
label_key: "target_gene_name"
batch_key: "gem_group"
eval_method: "reconstruct"

k_initial: 251
use_pca: true
distance_fx: "euclidean"

model_depth: 3
control_key: "target_gene_name"
control_label: "Non-targeting control"


max_epochs: 250
gpus: [0]
accelerator: "gpu"
precision: 32
distributed_backend: "ddp"

checkpoint_dir: "checkpoints"
checkpoint_monitor: "val_loss"
checkpoint_save_top_k: 1
checkpoint_mode: "min"

log_dir: "logs"
log_every_n_steps: 50

early_stop_monitor: "val_loss"
early_stop_patience: 10
early_stop_mode: "min"

bmdb_path: "./datasets/eval/internal_rxrx.h5ad"
recall_threshold : 0.05
bmdb_pert_col: "target_gene_name"
bmdb_ctrl_col: "target_gene_name"


wandb_project_name: "test_rxrx_PS"
wandb_entity: "valencelabs"